[[constraint]]
  branch = "master"
  name = "github.com/c9s/inflect"

[[constraint]]
  branch = "master"
  name = "github.com/crushedpixel/cement"

[[constraint]]
  branch = "master"
  name = "github.com/crushedpixel/ferry"

[[constraint]]
  name = "github.com/desertbit/glue"
  version = "1.9.1"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.9.3"

[[constraint]]
  name = "github.com/google/jsonapi"
  version = "1.0.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.5"

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.10.0"

[prune]
  go-tests = true
  unused-packages = true
