package internal

import (
	"reflect"
	"fmt"
	"errors"
	"github.com/iancoleman/strcase"
	"crushedpixel.net/jargo/api"
)

var errInvalidBelongsToType = errors.New("invalid belongsTo field type. for a belongsToMany relation, use many2many")

type belongsToField struct {
	*relationField

	joinJsonapiFields []reflect.StructField
	joinPGFields      []reflect.StructField
}

func newBelongsToField(r Registry, schema *schema, f *reflect.StructField, fk string) (field, error) {
	base, err := newRelationField(r, schema, f)
	if err != nil {
		return nil, err
	}

	if base.collection {
		return nil, errInvalidBelongsToType
	}

	field := &belongsToField{
		relationField: base,
	}

	// TODO: fail if there are invalid struct tag options

	return field, nil
}

func (f *belongsToField) pgFilterColumn() string {
	// the column name for the relation id field generated by go-pg
	// is a snake_cased version of the id field name
	return fmt.Sprintf("%s.%s", f.schema.alias, f.relationIdFieldColumn())
}

// override this function to calculate topLevel pg fields on demand,
// i.e. after non-top-level pg fields were calculated for reference.
func (f *belongsToField) pgFields() ([]reflect.StructField, error) {
	if f.pgF != nil {
		return f.pgF, nil
	}

	f.pgF = pgBelongsToFields(f, false)
	return f.pgF, nil
}

func (f *belongsToField) pgJoinFields() ([]reflect.StructField, error) {
	if f.joinPGFields != nil {
		return f.joinPGFields, nil
	}

	f.joinPGFields = pgBelongsToFields(f, true)
	return f.joinPGFields, nil
}

// generates the pg fields for a belongsTo relation. Example:
// Owner *User `jargo:",hasMany"
// =>
// OwnerId int64 // join model and full model
// Owner *User   // full model only
func pgBelongsToFields(f *belongsToField, joinField bool) []reflect.StructField {
	// every belongsTo association has a column containing
	// the id of the related resource
	tag := fmt.Sprintf(`sql:"%s`, f.relationIdFieldColumn())
	if f.sqlNotnull {
		tag += ",notnull"
	}
	if f.sqlUnique {
		tag += ",unique"
	}
	tag += `"`

	idField := reflect.StructField{
		Name: f.relationIdFieldName(),
		Type: idFieldType,
		Tag:  reflect.StructTag(tag),
	}
	fields := []reflect.StructField{idField}

	if !joinField {
		// non-join fields contain a reference
		// to the full pg model of the relation,
		// so relation data can be fetched in queries
		field := reflect.StructField{
			Name: f.fieldName,
			Type: f.relationJoinPGFieldType(),
		}
		fields = append(fields, field)
	}

	return fields
}

func (f *belongsToField) relationIdFieldName() string {
	return fmt.Sprintf("%sId", f.fieldName)
}

func (f *belongsToField) relationIdFieldColumn() string {
	return strcase.ToSnake(f.relationIdFieldName())
}

func (f *belongsToField) createInstance() fieldInstance {
	return &belongsToFieldInstance{
		relationFieldInstance: f.relationField.createInstance(),
		field:                 f,
	}
}

type belongsToFieldInstance struct {
	*relationFieldInstance
	field *belongsToField
}

func (i *belongsToFieldInstance) parentField() field {
	return i.field
}

// parses the value of the pg relation struct field (e.g. *User) and stores it
// in i.values[0]
func (i *belongsToFieldInstance) parsePGModel(instance *pgModelInstance) error {
	if i.field.schema != instance.schema {
		panic(errMismatchingSchema)
	}
	i.values = nil
	// do not parse nil models
	if instance.value.IsNil() {
		return nil
	}

	pgModelInstance := instance.value.Elem().FieldByName(i.field.fieldName).Interface()
	v, err := i.relationSchema.ParseJoinPGModel(pgModelInstance)
	if err != nil {
		return err
	}

	i.values = []api.SchemaInstance{v}
	return nil
}

// sets the value of the pg relation id field (e.g. UserId) to the id value
// of the schema instance stored in i.values[0]
func (i *belongsToFieldInstance) applyToPGModel(instance *pgModelInstance) error {
	if len(i.values) == 0 {
		return nil
	}

	// extract id field from relation and apply value
	// to pg id field
	v := i.values[0].(*schemaInstance)
	var id *int64
	for _, f := range v.fields {
		if idField, ok := f.(*idFieldInstance); ok {
			id = &idField.value
		}
	}
	if id == nil {
		panic(errors.New("id field of related resource not found"))
	}
	instance.value.Elem().FieldByName(i.field.relationIdFieldName()).SetInt(*id)

	// apply relation instance to pg model field
	joinPGModelInstance, err := v.ToJoinPGModel()
	if err != nil {
		return err
	}
	instance.value.Elem().FieldByName(i.field.fieldName).Set(reflect.ValueOf(joinPGModelInstance))
	return nil
}
